[settings]
disable_backends = ["ubi", "asdf"]
lockfile = true

[tools]
node = "lts"
"aqua:gittower/git-flow-next" = "2.0.0"
"aqua:j178/prek" = "0.5.4"
"npm:@fission-ai/openspec" = "1.14.0"

[env]
OPENSPEC_TELEMETRY = "0"
